# Generated by Django 4.1.1 on 2022-10-07 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Female',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('isPregnant', models.BooleanField(default=False)),
                ('dob', models.DateField(null=True)),
                ('estDob', models.DateField()),
                ('category', models.CharField(choices=[('mugongo', 'mugongo'), ('nduusi', 'nduusi'), ('kaluusi', 'kaluusi')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Male',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('dob', models.DateField(auto_now=True)),
                ('category', models.CharField(choices=[('nnume', 'nnume'), ('ndaawo', 'ndaawo'), ('kalume', 'kalume')], max_length=10)),
                ('father', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goat_management.male')),
                ('mother', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goat_management.female')),
            ],
        ),
        migrations.AddField(
            model_name='female',
            name='father',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goat_management.male'),
        ),
        migrations.AddField(
            model_name='female',
            name='mother',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goat_management.female'),
        ),
    ]
