# Generated by Django 4.1.1 on 2023-01-28 16:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Acaricide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("amount", models.IntegerField()),
                ("price", models.IntegerField()),
                ("date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Dewormer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("amount", models.IntegerField()),
                ("price", models.IntegerField()),
                ("date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("amount", models.IntegerField()),
                ("price", models.IntegerField()),
                ("date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("salary", models.IntegerField()),
                (
                    "last_payment",
                    models.DateField(
                        blank=True, default=datetime.date(2023, 1, 28), null=True
                    ),
                ),
                ("salary_paid", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("amount", models.IntegerField()),
                ("price", models.IntegerField()),
                ("date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Female",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("is_pregnant", models.BooleanField(default=False)),
                ("dob", models.DateField(null=True)),
                ("estDob", models.DateField(blank=True, default=None, null=True)),
                (
                    "gestdate",
                    models.DateField(
                        blank=True,
                        default=datetime.datetime(2023, 1, 28, 19, 14, 13, 749067),
                        null=True,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("mugongo", "mugongo"),
                            ("nduusi", "nduusi"),
                            ("kaluusi", "kaluusi"),
                        ],
                        max_length=10,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Male",
            fields=[
                (
                    "id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("dob", models.DateField(null=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("nnume", "nnume"),
                            ("ndaawo", "ndaawo"),
                            ("kalume", "kalume"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "father",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="goat_management.male",
                    ),
                ),
                (
                    "mother",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="goat_management.female",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Others",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("amount", models.IntegerField()),
                ("price", models.IntegerField()),
                ("date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PreviousProfit",
            fields=[
                (
                    "name",
                    models.CharField(max_length=250, primary_key=True, serialize=False),
                ),
                ("amount", models.IntegerField()),
                ("percent", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Todo",
            fields=[
                (
                    "name",
                    models.CharField(max_length=50, primary_key=True, serialize=False),
                ),
                ("complete", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Vaccine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("amount", models.IntegerField()),
                ("price", models.IntegerField()),
                ("date", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FDead",
            fields=[
                (
                    "f_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="goat_management.female",
                    ),
                ),
                ("DoD", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="FSold",
            fields=[
                (
                    "f_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="goat_management.female",
                    ),
                ),
                ("price", models.IntegerField()),
                ("DoS", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MDead",
            fields=[
                (
                    "m_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="goat_management.male",
                    ),
                ),
                ("DoD", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MSold",
            fields=[
                (
                    "m_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="goat_management.male",
                    ),
                ),
                ("price", models.IntegerField()),
                ("DoS", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Mating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "female",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goat_management.female",
                    ),
                ),
                (
                    "male",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goat_management.male",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="female",
            name="father",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="goat_management.male",
            ),
        ),
        migrations.AddField(
            model_name="female",
            name="mother",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="goat_management.female",
            ),
        ),
    ]
