# Generated by Django 4.1.1 on 2022-10-10 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goat_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='female',
            name='father',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goat_management.male'),
        ),
        migrations.AlterField(
            model_name='female',
            name='mother',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goat_management.female'),
        ),
        migrations.AlterField(
            model_name='male',
            name='father',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goat_management.male'),
        ),
        migrations.AlterField(
            model_name='male',
            name='mother',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goat_management.female'),
        ),
    ]
