# Generated by Django 4.1.1 on 2022-10-10 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goat_management', '0002_alter_female_father_alter_female_mother_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='male',
            name='dob',
            field=models.DateField(null=True),
        ),
    ]
