# Generated by Django 4.1.1 on 2022-10-10 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goat_management', '0003_alter_male_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambition',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('description', models.TextField(max_length=255)),
                ('dueDate', models.DateTimeField()),
                ('uploadDate', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
    ]
