# Generated by Django 4.1.1 on 2022-10-10 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goat_management', '0004_ambition_todo'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='id',
            field=models.IntegerField(default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
