# Generated by Django 4.1.1 on 2022-10-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goat_management', '0005_todo_id_alter_todo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
