# Generated by Django 4.1.1 on 2022-10-14 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goat_management', '0008_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='female',
            name='estDob',
            field=models.DateField(null=True),
        ),
    ]
