# Generated by Django 4.1.1 on 2022-10-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goat_management', '0009_alter_female_estdob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='female',
            name='estDob',
            field=models.DateField(blank=True, null=True),
        ),
    ]
