# Generated by Django 4.1.1 on 2022-10-25 16:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("goat_management", "0010_alter_female_estdob"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "female",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goat_management.female",
                    ),
                ),
                (
                    "male",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goat_management.male",
                    ),
                ),
            ],
        ),
    ]
