# Generated by Django 4.1.1 on 2022-10-28 11:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goat_management', '0011_mating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('start_date', models.DateField(auto_now=True)),
                ('last_payment', models.DateField(blank=True, default=datetime.date(2022, 10, 28), null=True)),
                ('salary_paid', models.BooleanField()),
            ],
        ),
    ]
