# Generated by Django 4.1.1 on 2022-10-28 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goat_management', '0012_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dead',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('dob', models.DateField(null=True)),
                ('category', models.CharField(max_length=10)),
                ('father', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goat_management.male')),
                ('mother', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goat_management.female')),
            ],
        ),
    ]
