# Generated by Django 4.1.1 on 2022-11-01 16:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("goat_management", "0013_dead"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alive",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=6
                    ),
                ),
                (
                    "f_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goat_management.male",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Sold",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=6
                    ),
                ),
                (
                    "f_id",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goat_management.male",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UnSold",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=6
                    ),
                ),
                (
                    "f_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goat_management.male",
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_payment",
            field=models.DateField(
                blank=True, default=datetime.date(2022, 11, 1), null=True
            ),
        ),
        migrations.DeleteModel(
            name="Dead",
        ),
    ]
