# Generated by Django 4.1.1 on 2022-11-01 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "goat_management",
            "0014_alive_sold_unsold_alter_employee_last_payment_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Dead",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=6
                    ),
                ),
                (
                    "f_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goat_management.male",
                    ),
                ),
            ],
        ),
    ]
