# Generated by Django 4.1.1 on 2022-11-01 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goat_management", "0015_dead"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="unsold",
            name="f_id",
        ),
        migrations.AddField(
            model_name="sold",
            name="price",
            field=models.IntegerField(default=300000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dead",
            name="f_id",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="sold",
            name="f_id",
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name="Alive",
        ),
        migrations.DeleteModel(
            name="UnSold",
        ),
    ]
