# Generated by Django 4.1.1 on 2022-11-04 09:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "goat_management",
            "0016_remove_unsold_f_id_sold_price_alter_dead_f_id_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="last_payment",
            field=models.DateField(
                blank=True, default=datetime.date(2022, 11, 4), null=True
            ),
        ),
    ]
