# Generated by Django 4.1.1 on 2022-11-04 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("goat_management", "0017_alter_employee_last_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="FDead",
            fields=[
                (
                    "f_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="goat_management.male",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MDead",
            fields=[
                (
                    "m_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="goat_management.male",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Dead",
        ),
    ]
