# Generated by Django 4.1.1 on 2022-11-04 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("goat_management", "0018_fdead_mdead_delete_dead"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fdead",
            name="f_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                primary_key=True,
                serialize=False,
                to="goat_management.female",
            ),
        ),
    ]
