# Generated by Django 4.1.1 on 2022-11-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goat_management", "0019_alter_fdead_f_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="female",
            name="estDob",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
