# Generated by Django 4.1.1 on 2022-11-06 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goat_management", "0020_alter_female_estdob"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="employee",
            name="start_date",
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_payment",
            field=models.DateField(
                blank=True, default=datetime.date(2022, 11, 6), null=True
            ),
        ),
    ]
