# Generated by Django 4.1.1 on 2022-11-07 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goat_management", "0021_remove_employee_start_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="last_payment",
            field=models.DateField(
                blank=True, default=datetime.date(2022, 11, 7), null=True
            ),
        ),
    ]
