# Generated by Django 4.1.1 on 2022-11-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goat_management", "0022_alter_employee_last_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="mdead",
            name="DoD",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
