# Generated by Django 4.1.1 on 2022-11-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goat_management", "0024_fdead_dod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fdead",
            name="DoD",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="mdead",
            name="DoD",
            field=models.DateField(blank=True, null=True),
        ),
    ]
