# Generated by Django 4.1.1 on 2022-11-07 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("goat_management", "0025_alter_fdead_dod_alter_mdead_dod"),
    ]

    operations = [
        migrations.CreateModel(
            name="FSold",
            fields=[
                (
                    "f_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="goat_management.female",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=6
                    ),
                ),
                ("price", models.IntegerField()),
                ("DoS", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MSold",
            fields=[
                (
                    "f_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to="goat_management.male",
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=6
                    ),
                ),
                ("price", models.IntegerField()),
                ("DoS", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Sold",
        ),
    ]
