# Generated by Django 4.1.1 on 2022-11-07 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goat_management", "0026_fsold_msold_delete_sold"),
    ]

    operations = [
        migrations.RenameField(
            model_name="msold",
            old_name="f_id",
            new_name="m_id",
        ),
    ]
