# Generated by Django 4.1.1 on 2022-11-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goat_management", "0027_rename_f_id_msold_m_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="female",
            name="estDob",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
