# Generated by Django 4.1.1 on 2022-11-07 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goat_management", "0029_alter_female_estdob"),
    ]

    operations = [
        migrations.AddField(
            model_name="female",
            name="gestdate",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
