# Generated by Django 4.1.1 on 2022-11-14 17:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("goat_management", "0030_female_gestdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="last_payment",
            field=models.DateField(
                blank=True, default=datetime.date(2022, 11, 14), null=True
            ),
        ),
        migrations.AlterField(
            model_name="mating",
            name="female",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="goat_management.female",
            ),
        ),
        migrations.AlterField(
            model_name="mating",
            name="male",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="goat_management.male",
            ),
        ),
    ]
