# Generated by Django 4.1.1 on 2022-11-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "goat_management",
            "0031_alter_employee_last_payment_alter_mating_female_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Acaricide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("amount", models.IntegerField()),
                ("price", models.IntegerField()),
                ("date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Deworming",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("amount", models.IntegerField()),
                ("price", models.IntegerField()),
                ("date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Drug",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("amount", models.IntegerField()),
                ("price", models.IntegerField()),
                ("date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Feed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("amount", models.IntegerField()),
                ("price", models.IntegerField()),
                ("date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Vaccine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("amount", models.IntegerField()),
                ("price", models.IntegerField()),
                ("date", models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
