# Generated by Django 4.1.1 on 2022-11-14 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goat_management", "0032_acaricide_deworming_drug_feed_vaccine"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Deworming",
            new_name="Dewormer",
        ),
    ]
