# Generated by Django 4.1.1 on 2022-11-23 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goat_management", "0035_others_alter_employee_last_payment"),
    ]

    operations = [
        migrations.CreateModel(
            name="PreviousProfit",
            fields=[
                (
                    "name",
                    models.CharField(max_length=250, primary_key=True, serialize=False),
                ),
                ("amount", models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_payment",
            field=models.DateField(
                blank=True, default=datetime.date(2022, 11, 23), null=True
            ),
        ),
    ]
