# Generated by Django 4.1.1 on 2022-11-23 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goat_management", "0036_previousprofit_alter_employee_last_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="acaricide",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="dewormer",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="drug",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="feed",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="others",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vaccine",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
