# Generated by Django 4.1.1 on 2022-11-23 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goat_management", "0037_alter_acaricide_date_alter_dewormer_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="previousprofit",
            name="date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
