# Generated by Django 4.1.1 on 2022-11-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goat_management", "0038_previousprofit_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="previousprofit",
            name="date",
        ),
        migrations.AddField(
            model_name="previousprofit",
            name="percent",
            field=models.IntegerField(default=0),
        ),
    ]
