# Generated by Django 4.1.1 on 2022-11-23 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goat_management", "0039_remove_previousprofit_date_previousprofit_percent"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="complete",
            field=models.BooleanField(default=False),
        ),
    ]
