# Generated by Django 4.1.1 on 2022-11-24 19:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goat_management", "0041_remove_todo_id_alter_todo_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="fsold",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="msold",
            name="gender",
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_payment",
            field=models.DateField(
                blank=True, default=datetime.date(2022, 11, 24), null=True
            ),
        ),
    ]
