# Generated by Django 4.1.1 on 2022-11-25 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goat_management", "0042_remove_fsold_gender_remove_msold_gender_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="female",
            old_name="isPregnant",
            new_name="is_pregnant",
        ),
        migrations.AlterField(
            model_name="employee",
            name="last_payment",
            field=models.DateField(
                blank=True, default=datetime.date(2022, 11, 25), null=True
            ),
        ),
    ]
