# Generated by Django 4.1.1 on 2022-11-25 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goat_management", "0043_rename_ispregnant_female_is_pregnant_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="female",
            name="gestdate",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(2022, 11, 25, 18, 36, 33, 811104),
                null=True,
            ),
        ),
    ]
