# Generated by Django 4.1.1 on 2023-01-20 14:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goat_management", "0045_alter_employee_last_payment_alter_female_gestdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="female",
            name="gestdate",
            field=models.DateField(
                blank=True,
                default=datetime.datetime(2023, 1, 20, 17, 27, 41, 818805),
                null=True,
            ),
        ),
    ]
