# Generated by Django 4.1.1 on 2022-10-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f_name', models.CharField(max_length=50)),
                ('salary', models.IntegerField()),
                ('start_date', models.DateField(auto_now=True)),
                ('salary_paid', models.BooleanField()),
            ],
        ),
    ]
