# Generated by Django 4.1.1 on 2022-10-21 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='last_payment',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
