# Generated by Django 4.1.1 on 2022-10-21 13:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_employee_last_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='last_payment',
            field=models.DateField(blank=True, default=datetime.date(2022, 10, 21), null=True),
        ),
    ]
