# Generated by Django 4.1.1 on 2022-10-25 14:59

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("goat_management", "0010_alter_female_estdob"),
        ("main_app", "0006_alter_employee_last_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="last_payment",
            field=models.DateField(
                blank=True, default=datetime.date(2022, 10, 25), null=True
            ),
        ),
        migrations.CreateModel(
            name="Mating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "female",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="goat_management.female",
                    ),
                ),
                (
                    "male",
                    models.ForeignKey(
                        blank=True,
                        default=None,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="goat_management.male",
                    ),
                ),
            ],
        ),
    ]
