# Generated by Django 4.1.1 on 2022-10-25 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0007_alter_employee_last_payment_mating"),
    ]

    operations = [
        migrations.DeleteModel(name="Mating",),
    ]
