# Generated by Django 4.1.1 on 2022-10-28 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_delete_mating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
