# Generated by Django 4.1.1 on 2022-11-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0010_acaricide_deworming_drug_feed_vaccine"),
    ]

    operations = [
        migrations.AddField(
            model_name="acaricide",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deworming",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="drug",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feed",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vaccine",
            name="date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
