# Generated by Django 4.1.1 on 2022-11-14 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0011_acaricide_date_deworming_date_drug_date_feed_date_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Acaricide",
        ),
        migrations.DeleteModel(
            name="Deworming",
        ),
        migrations.DeleteModel(
            name="Drug",
        ),
        migrations.DeleteModel(
            name="Feed",
        ),
        migrations.DeleteModel(
            name="Vaccine",
        ),
    ]
