# Generated by Django 4.1.1 on 2023-01-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main_app", "0012_delete_acaricide_delete_deworming_delete_drug_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="id",
        ),
        migrations.AddField(
            model_name="todo",
            name="complete",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="todo",
            name="name",
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
